### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableSet

### ISSUE THREAD

**Issue by szd0000** [asari-mtr/presto-udaf#1]
Hello, when learning this demo, this problem arises, I hope you can give guidance, thank you.

2018-05-21T10:15:33.981+0800	INFO	main	com.facebook.presto.server.PluginManager	-- Loading plugin /opt/presto/presto-data/plugin/xqy-functions --
2018-05-21T10:15:34.036+0800	INFO	main	com.facebook.presto.server.PluginManager	Installing demo.presto_demo.AnswerToLifePlugin
2018-05-21T10:15:34.036+0800	ERROR	main	com.facebook.presto.server.PrestoServer	com/google/common/collect/ImmutableSet
java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableSet
	at demo.presto_demo.AnswerToLifePlugin.getFunctions(AnswerToLifePlugin.java:13)
	at com.facebook.presto.server.PluginManager.installPlugin(PluginManager.java:198)
	at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:172)
	at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:156)
	at com.facebook.presto.server.PluginManager.loadPlugins(PluginManager.java:137)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:117)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableSet
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.facebook.presto.server.PluginClassLoader.loadClass(PluginClassLoader.java:80)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by asari-mtr** [comment]
Thank you for using this repository.

What is your presto version?
Older versions of presto may not include `google.commons` dependencies.

Or, if you are using the master branch, you may want to use the `stackoverflow` branch.

I check the operation with the `stackoverflow` branch, but I have not confirmed the operation on the master branch.
`stackoverflow` blanch was confirmed with presto 0.188 on EMR.

**Comment by szd0000** [comment]
Thank you for answering my question.
Because just contact presto, is a beginner, so many places do not understand, forgive me!
My version of Presto is 0.201
I created the project myself, and the code was copied into it. Maybe there was a problem.
My POM file:

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>presto-demo</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<name>demo</name>
	<url>http://maven.apache.org</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

 	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.11</version>
			<scope>test</scope>
		</dependency>



		
		<dependency>
			<groupId>com.facebook.presto</groupId>
			<artifactId>presto-spi</artifactId>
			<version>0.201</version>
			<scope>provided</scope>
		</dependency>

		
		<dependency>
			<groupId>com.facebook.presto</groupId>
			<artifactId>presto-array</artifactId>
			<version>0.201</version>
		</dependency>
		
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>23.0</version>
		</dependency>


	</dependencies>

        <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    
</project>

**Comment by asari-mtr** [comment]
Try adding `presto-plugin` to packaging in your pom.xml and add the following code.
(please reference this code [pom.xml](https://github.com/asari-mtr/presto-udaf/blob/fecc16db676b86668ba37897bf94e881f2f6456c/pom.xml))
``` xml
    <build>
        <plugins>
            ...
            <plugin>
                <groupId>com.facebook.presto</groupId>
                <artifactId>presto-maven-plugin</artifactId>
                <version>0.3</version>
                <extensions>true</extensions>
            </plugin>
        </plugins>
    </build>
```

Running `mvn clean install` will create a zip file under the target directory.
Since it contains the required jar, you can run your own plugin by constantly deploying it presto.

**Comment by szd0000** [comment]
Thank you very much for your help
I've solved my problem, thank you.
